UI tests
ealpyspa/teamcity-testing-framework pull request #2
Opened 2024-11-03 20:00 UTC by ealpyspa

2024-11-10 22:30 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась на API уровне в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-10 22:30 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildConfigurationTest.java
> +        softy.assertTrue(foundBuilds);
Отлично!

2024-11-10 22:30 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildConfigurationTest.java
> +        // даже когда count не был пустым
Ты имеешь в виду, что не смогла получить количество?

2024-11-13 09:06 UTC, ealpyspa commented on src/test/java/com/example/teamcity/ui/CreateBuildConfigurationTest.java
> +        // даже когда count не был пустым
Количество смогла получить, не заполнялись buildTypes. Я переделала и теперь вытаскиваю только count.

2024-11-13 12:49 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildConfigurationTest.java
> +        // даже когда count не был пустым
Отлично, спасибо!

2024-11-13 16:13 UTC, merged